--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create bg
local bg=cc.Node:create()
bg:setName("bg")
bg:setTag(69)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
Node:addChild(bg)

--Create hall_room_bg_2_2
local hall_room_bg_2_2 = cc.Sprite:create("hall/friend/fr_bg_1.png")
hall_room_bg_2_2:setName("hall_room_bg_2_2")
hall_room_bg_2_2:setTag(71)
hall_room_bg_2_2:setCascadeColorEnabled(true)
hall_room_bg_2_2:setCascadeOpacityEnabled(true)
hall_room_bg_2_2:setPosition(0.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bg_2_2)
layout:setSize({width = 351.0000, height = 351.0000})
layout:setLeftMargin(-175.5000)
layout:setRightMargin(-175.5000)
layout:setTopMargin(-205.5000)
layout:setBottomMargin(-145.5000)
hall_room_bg_2_2:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bg_2_2)

--Create fish
local fish=cc.Node:create()
fish:setName("fish")
fish:setTag(93)
fish:setCascadeColorEnabled(true)
fish:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(fish)
Node:addChild(fish)

--Create fr_fish_3_cannon
local fr_fish_3_cannon = cc.Sprite:create("hall/friend/fr_fish_3_cannon.png")
fr_fish_3_cannon:setName("fr_fish_3_cannon")
fr_fish_3_cannon:setTag(26)
fr_fish_3_cannon:setCascadeColorEnabled(true)
fr_fish_3_cannon:setCascadeOpacityEnabled(true)
fr_fish_3_cannon:setAnchorPoint(0.3319, 0.3445)
fr_fish_3_cannon:setPosition(-52.9655, 64.8800)
layout = ccui.LayoutComponent:bindLayoutComponent(fr_fish_3_cannon)
layout:setSize({width = 280.0000, height = 220.0000})
layout:setLeftMargin(-145.8877)
layout:setRightMargin(-134.1123)
layout:setTopMargin(-209.0830)
layout:setBottomMargin(-10.9170)
fr_fish_3_cannon:setBlendFunc({src = 1, dst = 771})
fish:addChild(fr_fish_3_cannon)

--Create hand_0
local hand_0 = cc.Sprite:create("hall/friend/fr_fish_3_hand_3.png")
hand_0:setName("hand_0")
hand_0:setTag(25)
hand_0:setCascadeColorEnabled(true)
hand_0:setCascadeOpacityEnabled(true)
hand_0:setAnchorPoint(0.0000, 0.0000)
hand_0:setPosition(86.6233, -9.1364)
hand_0:setRotationSkewX(-3.6955)
hand_0:setRotationSkewY(-3.6951)
layout = ccui.LayoutComponent:bindLayoutComponent(hand_0)
layout:setSize({width = 37.0000, height = 23.0000})
layout:setLeftMargin(86.6233)
layout:setRightMargin(-123.6233)
layout:setTopMargin(-13.8636)
layout:setBottomMargin(-9.1364)
hand_0:setBlendFunc({src = 1, dst = 771})
fish:addChild(hand_0)

--Create hall_room_fish_2_7
local hall_room_fish_2_7 = cc.Sprite:create("hall/friend/fr_fish_3.png")
hall_room_fish_2_7:setName("hall_room_fish_2_7")
hall_room_fish_2_7:setTag(77)
hall_room_fish_2_7:setCascadeColorEnabled(true)
hall_room_fish_2_7:setCascadeOpacityEnabled(true)
hall_room_fish_2_7:setPosition(-2.0000, 11.0000)
hall_room_fish_2_7:setScaleY(0.9500)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_2_7)
layout:setSize({width = 207.0000, height = 166.0000})
layout:setLeftMargin(-105.5000)
layout:setRightMargin(-101.5000)
layout:setTopMargin(-94.0000)
layout:setBottomMargin(-72.0000)
hall_room_fish_2_7:setBlendFunc({src = 1, dst = 771})
fish:addChild(hall_room_fish_2_7)

--Create eyes
local eyes=cc.Node:create()
eyes:setName("eyes")
eyes:setTag(158)
eyes:setCascadeColorEnabled(true)
eyes:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(eyes)
fish:addChild(eyes)

--Create spr_eyes_1
local spr_eyes_1 = cc.Sprite:create("hall/friend/fr_fish_3_bg_1.png")
spr_eyes_1:setName("spr_eyes_1")
spr_eyes_1:setTag(159)
spr_eyes_1:setCascadeColorEnabled(true)
spr_eyes_1:setCascadeOpacityEnabled(true)
spr_eyes_1:setAnchorPoint(0.1820, 0.0000)
spr_eyes_1:setPosition(19.1328, 32.8000)
spr_eyes_1:setScaleX(0.6000)
spr_eyes_1:setScaleY(0.6000)
spr_eyes_1:setRotationSkewY(-0.0004)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_eyes_1)
layout:setSize({width = 41.0000, height = 94.0000})
layout:setLeftMargin(11.6708)
layout:setRightMargin(-52.6708)
layout:setTopMargin(-126.8000)
layout:setBottomMargin(32.8000)
spr_eyes_1:setBlendFunc({src = 1, dst = 771})
eyes:addChild(spr_eyes_1)

--Create spr_eyes_2
local spr_eyes_2 = cc.Sprite:create("hall/friend/fr_fish_3_bg_2.png")
spr_eyes_2:setName("spr_eyes_2")
spr_eyes_2:setTag(160)
spr_eyes_2:setCascadeColorEnabled(true)
spr_eyes_2:setCascadeOpacityEnabled(true)
spr_eyes_2:setAnchorPoint(0.0700, 0.0400)
spr_eyes_2:setPosition(42.8598, 31.1798)
spr_eyes_2:setScaleX(0.6000)
spr_eyes_2:setScaleY(0.6000)
spr_eyes_2:setRotationSkewY(0.0009)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_eyes_2)
layout:setSize({width = 80.0000, height = 87.0000})
layout:setLeftMargin(37.2598)
layout:setRightMargin(-117.2598)
layout:setTopMargin(-114.6998)
layout:setBottomMargin(27.6998)
spr_eyes_2:setBlendFunc({src = 1, dst = 771})
eyes:addChild(spr_eyes_2)

--Create spr_eyes_4
local spr_eyes_4 = cc.Sprite:create("hall/friend/fr_fish_3_eyes_2.png")
spr_eyes_4:setName("spr_eyes_4")
spr_eyes_4:setTag(24)
spr_eyes_4:setCascadeColorEnabled(true)
spr_eyes_4:setCascadeOpacityEnabled(true)
spr_eyes_4:setPosition(94.4965, 99.8846)
spr_eyes_4:setScaleX(0.9000)
spr_eyes_4:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_eyes_4)
layout:setSize({width = 78.0000, height = 76.0000})
layout:setLeftMargin(55.4965)
layout:setRightMargin(-133.4965)
layout:setTopMargin(-137.8846)
layout:setBottomMargin(61.8846)
spr_eyes_4:setBlendFunc({src = 1, dst = 771})
eyes:addChild(spr_eyes_4)

--Create spr_eyes_3
local spr_eyes_3 = cc.Sprite:create("hall/friend/fr_fish_3_eyes_1.png")
spr_eyes_3:setName("spr_eyes_3")
spr_eyes_3:setTag(23)
spr_eyes_3:setCascadeColorEnabled(true)
spr_eyes_3:setCascadeOpacityEnabled(true)
spr_eyes_3:setPosition(36.3073, 112.7878)
spr_eyes_3:setScaleX(0.9100)
spr_eyes_3:setScaleY(0.9100)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_eyes_3)
layout:setSize({width = 80.0000, height = 81.0000})
layout:setLeftMargin(-3.6927)
layout:setRightMargin(-76.3073)
layout:setTopMargin(-153.2878)
layout:setBottomMargin(72.2878)
spr_eyes_3:setBlendFunc({src = 1, dst = 771})
eyes:addChild(spr_eyes_3)

--Create hand_1
local hand_1 = cc.Sprite:create("hall/friend/fr_fish_3_hand_1.png")
hand_1:setName("hand_1")
hand_1:setTag(46)
hand_1:setCascadeColorEnabled(true)
hand_1:setCascadeOpacityEnabled(true)
hand_1:setAnchorPoint(0.0000, 0.5000)
hand_1:setPosition(107.9464, -2.1603)
hand_1:setRotationSkewY(0.0005)
layout = ccui.LayoutComponent:bindLayoutComponent(hand_1)
layout:setSize({width = 119.0000, height = 122.0000})
layout:setLeftMargin(107.9464)
layout:setRightMargin(-226.9464)
layout:setTopMargin(-58.8397)
layout:setBottomMargin(-63.1603)
hand_1:setBlendFunc({src = 1, dst = 771})
fish:addChild(hand_1)

--Create hand_2
local hand_2 = cc.Sprite:create("hall/friend/fr_fish_3_hand_2.png")
hand_2:setName("hand_2")
hand_2:setTag(47)
hand_2:setCascadeColorEnabled(true)
hand_2:setCascadeOpacityEnabled(true)
hand_2:setAnchorPoint(0.2054, 0.8700)
hand_2:setPosition(-62.2308, 24.7985)
hand_2:setRotationSkewY(-0.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(hand_2)
layout:setSize({width = 105.0000, height = 115.0000})
layout:setLeftMargin(-83.7928)
layout:setRightMargin(-21.2072)
layout:setTopMargin(-39.7485)
layout:setBottomMargin(-75.2515)
hand_2:setBlendFunc({src = 1, dst = 771})
fish:addChild(hand_2)

--Create room_effect
local room_effect=cc.Node:create()
room_effect:setName("room_effect")
room_effect:setTag(76)
room_effect:setCascadeColorEnabled(true)
room_effect:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(room_effect)
Node:addChild(room_effect)

--Create hall_room_effect_1_1_3
local hall_room_effect_1_1_3 = cc.Sprite:create("hall/friend/fr_bg_aquatic_1.png")
hall_room_effect_1_1_3:setName("hall_room_effect_1_1_3")
hall_room_effect_1_1_3:setTag(104)
hall_room_effect_1_1_3:setCascadeColorEnabled(true)
hall_room_effect_1_1_3:setCascadeOpacityEnabled(true)
hall_room_effect_1_1_3:setPosition(-130.0000, -60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_1_1_3)
layout:setSize({width = 88.0000, height = 104.0000})
layout:setLeftMargin(-174.0000)
layout:setRightMargin(86.0000)
layout:setTopMargin(8.0000)
layout:setBottomMargin(-112.0000)
hall_room_effect_1_1_3:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_1_1_3)

--Create hall_room_effect_1_2_4
local hall_room_effect_1_2_4 = cc.Sprite:create("hall/friend/fr_bg_aquatic_2.png")
hall_room_effect_1_2_4:setName("hall_room_effect_1_2_4")
hall_room_effect_1_2_4:setTag(105)
hall_room_effect_1_2_4:setCascadeColorEnabled(true)
hall_room_effect_1_2_4:setCascadeOpacityEnabled(true)
hall_room_effect_1_2_4:setPosition(-80.0000, -60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_1_2_4)
layout:setSize({width = 122.0000, height = 148.0000})
layout:setLeftMargin(-141.0000)
layout:setRightMargin(19.0000)
layout:setTopMargin(-14.0000)
layout:setBottomMargin(-134.0000)
hall_room_effect_1_2_4:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_1_2_4)

--Create hall_room_effect_1_4_6
local hall_room_effect_1_4_6 = cc.Sprite:create("hall/friend/fr_bg_aquatic_4.png")
hall_room_effect_1_4_6:setName("hall_room_effect_1_4_6")
hall_room_effect_1_4_6:setTag(107)
hall_room_effect_1_4_6:setCascadeColorEnabled(true)
hall_room_effect_1_4_6:setCascadeOpacityEnabled(true)
hall_room_effect_1_4_6:setPosition(124.7764, -43.5390)
hall_room_effect_1_4_6:setRotationSkewX(9.3639)
hall_room_effect_1_4_6:setRotationSkewY(9.3630)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_1_4_6)
layout:setSize({width = 130.0000, height = 128.0000})
layout:setLeftMargin(59.7764)
layout:setRightMargin(-189.7764)
layout:setTopMargin(-20.4610)
layout:setBottomMargin(-107.5390)
hall_room_effect_1_4_6:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_1_4_6)

--Create hall_room_effect_1_3_5
local hall_room_effect_1_3_5 = cc.Sprite:create("hall/friend/fr_bg_aquatic_3.png")
hall_room_effect_1_3_5:setName("hall_room_effect_1_3_5")
hall_room_effect_1_3_5:setTag(106)
hall_room_effect_1_3_5:setCascadeColorEnabled(true)
hall_room_effect_1_3_5:setCascadeOpacityEnabled(true)
hall_room_effect_1_3_5:setPosition(75.5117, -30.0706)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_1_3_5)
layout:setSize({width = 130.0000, height = 134.0000})
layout:setLeftMargin(10.5117)
layout:setRightMargin(-140.5117)
layout:setTopMargin(-36.9294)
layout:setBottomMargin(-97.0706)
hall_room_effect_1_3_5:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_1_3_5)

--Create title
local title=cc.Node:create()
title:setName("title")
title:setTag(80)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
title:setPosition(0.0000, -22.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(title)
layout:setTopMargin(22.0000)
layout:setBottomMargin(-22.0000)
Node:addChild(title)

--Create hall_room_title_2_9
local hall_room_title_2_9 = cc.Sprite:create("hall/friend/fr_pic_dkfj_1.png")
hall_room_title_2_9:setName("hall_room_title_2_9")
hall_room_title_2_9:setTag(79)
hall_room_title_2_9:setCascadeColorEnabled(true)
hall_room_title_2_9:setCascadeOpacityEnabled(true)
hall_room_title_2_9:setPosition(0.0000, -86.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_2_9)
layout:setSize({width = 278.0000, height = 98.0000})
layout:setLeftMargin(-139.0000)
layout:setRightMargin(-139.0000)
layout:setTopMargin(37.0000)
layout:setBottomMargin(-135.0000)
hall_room_title_2_9:setBlendFunc({src = 1, dst = 771})
title:addChild(hall_room_title_2_9)

--Create hall_room_title_light_3_14
local hall_room_title_light_3_14 = cc.Sprite:create("hall/room/hall_room_title_light_3.png")
hall_room_title_light_3_14:setName("hall_room_title_light_3_14")
hall_room_title_light_3_14:setTag(85)
hall_room_title_light_3_14:setCascadeColorEnabled(true)
hall_room_title_light_3_14:setCascadeOpacityEnabled(true)
hall_room_title_light_3_14:setPosition(128.4567, -43.3778)
hall_room_title_light_3_14:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_3_14)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(103.4567)
layout:setRightMargin(-153.4567)
layout:setTopMargin(18.3778)
layout:setBottomMargin(-68.3778)
hall_room_title_light_3_14:setBlendFunc({src = 1, dst = 1})
title:addChild(hall_room_title_light_3_14)

--Create run_light
local run_light = ccui.Layout:create()
run_light:ignoreContentAdaptWithSize(false)
run_light:setClippingEnabled(true)
run_light:setBackGroundColorOpacity(102)
run_light:setLayoutComponentEnabled(true)
run_light:setName("run_light")
run_light:setTag(86)
run_light:setCascadeColorEnabled(true)
run_light:setCascadeOpacityEnabled(true)
run_light:setPosition(-130.7661, -119.5507)
run_light:setScaleX(1.2800)
run_light:setScaleY(0.3025)
run_light:setRotationSkewX(5.9993)
run_light:setRotationSkewY(-4.0006)
layout = ccui.LayoutComponent:bindLayoutComponent(run_light)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(-130.7661)
layout:setRightMargin(-69.2339)
layout:setTopMargin(-80.4493)
layout:setBottomMargin(-119.5507)
title:addChild(run_light)

--Create hall_room_title_light_1_13
local hall_room_title_light_1_13 = cc.Sprite:create("hall/room/hall_room_title_light_1.png")
hall_room_title_light_1_13:setName("hall_room_title_light_1_13")
hall_room_title_light_1_13:setTag(84)
hall_room_title_light_1_13:setCascadeColorEnabled(true)
hall_room_title_light_1_13:setCascadeOpacityEnabled(true)
hall_room_title_light_1_13:setPosition(-32.4290, 97.2122)
hall_room_title_light_1_13:setScaleX(0.8000)
hall_room_title_light_1_13:setScaleY(2.4847)
hall_room_title_light_1_13:setRotationSkewX(-2.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_1_13)
layout:setPositionPercentX(-0.1621)
layout:setPositionPercentY(0.4861)
layout:setPercentWidth(0.4700)
layout:setPercentHeight(0.5200)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(-79.4290)
layout:setRightMargin(185.4290)
layout:setTopMargin(50.7878)
layout:setBottomMargin(45.2122)
hall_room_title_light_1_13:setBlendFunc({src = 774, dst = 1})
run_light:addChild(hall_room_title_light_1_13)

--Create hall_room_title_light_1_13_0
local hall_room_title_light_1_13_0 = cc.Sprite:create("hall/room/hall_room_title_light_1.png")
hall_room_title_light_1_13_0:setName("hall_room_title_light_1_13_0")
hall_room_title_light_1_13_0:setTag(96)
hall_room_title_light_1_13_0:setCascadeColorEnabled(true)
hall_room_title_light_1_13_0:setCascadeOpacityEnabled(true)
hall_room_title_light_1_13_0:setPosition(-32.4290, 97.2122)
hall_room_title_light_1_13_0:setScaleX(0.8000)
hall_room_title_light_1_13_0:setScaleY(2.4847)
hall_room_title_light_1_13_0:setRotationSkewX(-2.0000)
hall_room_title_light_1_13_0:setOpacity(127)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_1_13_0)
layout:setPositionPercentX(-0.1621)
layout:setPositionPercentY(0.4861)
layout:setPercentWidth(0.4700)
layout:setPercentHeight(0.5200)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(-79.4290)
layout:setRightMargin(185.4290)
layout:setTopMargin(50.7878)
layout:setBottomMargin(45.2122)
hall_room_title_light_1_13_0:setBlendFunc({src = 774, dst = 1})
run_light:addChild(hall_room_title_light_1_13_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(120)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(5.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(bg)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(bg)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-52.9655)
localFrame:setY(64.8800)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-52.9655)
localFrame:setY(64.8800)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(fr_fish_3_cannon)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(fr_fish_3_cannon)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-5.5616)
localFrame:setSkewY(-5.5607)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(fr_fish_3_cannon)

--Create AnchorPointTimeline
local AnchorPointTimeline = ccs.Timeline:create()

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0.3319, y = 0.3445})
AnchorPointTimeline:addFrame(localFrame)

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0.3319, y = 0.3445})
AnchorPointTimeline:addFrame(localFrame)

result['animation']:addTimeline(AnchorPointTimeline)
AnchorPointTimeline:setNode(fr_fish_3_cannon)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(86.6233)
localFrame:setY(-9.1364)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(86.6168)
localFrame:setY(-8.4581)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(86.6233)
localFrame:setY(-9.1364)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hand_0)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-3.6955)
localFrame:setSkewY(-3.6951)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hand_0)

--Create AnchorPointTimeline
local AnchorPointTimeline = ccs.Timeline:create()

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0, y = 0})
AnchorPointTimeline:addFrame(localFrame)

result['animation']:addTimeline(AnchorPointTimeline)
AnchorPointTimeline:setNode(hand_0)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(0.9500)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9500)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(0.9500)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_2_7)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-2.0000)
localFrame:setY(11.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_2_7)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_fish_2_7)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(19.1328)
localFrame:setY(32.8000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(18.0600)
localFrame:setY(34.8016)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(19.1328)
localFrame:setY(32.8000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(spr_eyes_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.6000)
localFrame:setScaleY(0.6000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(spr_eyes_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(-0.0004)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-7.0000)
localFrame:setSkewY(-7.0004)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(spr_eyes_1)

--Create AnchorPointTimeline
local AnchorPointTimeline = ccs.Timeline:create()

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0.182, y = 0})
AnchorPointTimeline:addFrame(localFrame)

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0.182, y = 0})
AnchorPointTimeline:addFrame(localFrame)

result['animation']:addTimeline(AnchorPointTimeline)
AnchorPointTimeline:setNode(spr_eyes_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(42.8598)
localFrame:setY(31.1798)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(41.2089)
localFrame:setY(31.8402)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(42.8598)
localFrame:setY(31.1798)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(spr_eyes_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.6000)
localFrame:setScaleY(0.6000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(spr_eyes_2)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0009)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(5.9707)
localFrame:setSkewY(5.9716)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(spr_eyes_2)

--Create AnchorPointTimeline
local AnchorPointTimeline = ccs.Timeline:create()

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0.07, y = 0.04})
AnchorPointTimeline:addFrame(localFrame)

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0.07, y = 0.04})
AnchorPointTimeline:addFrame(localFrame)

result['animation']:addTimeline(AnchorPointTimeline)
AnchorPointTimeline:setNode(spr_eyes_2)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(94.4965)
localFrame:setY(99.8846)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(102.7035)
localFrame:setY(92.7970)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(94.4965)
localFrame:setY(99.8846)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(spr_eyes_4)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(spr_eyes_4)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(13.0717)
localFrame:setSkewY(13.0716)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(spr_eyes_4)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(spr_eyes_4)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(36.3073)
localFrame:setY(112.7878)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(25.2399)
localFrame:setY(113.3347)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(36.3073)
localFrame:setY(112.7878)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(spr_eyes_3)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9100)
localFrame:setScaleY(0.9100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9100)
localFrame:setScaleY(0.9100)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(spr_eyes_3)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-6.3711)
localFrame:setSkewY(-6.3707)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(spr_eyes_3)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(spr_eyes_3)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(107.9464)
localFrame:setY(-2.1603)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(106.5929)
localFrame:setY(1.4481)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(107.9464)
localFrame:setY(-2.1603)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hand_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hand_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0005)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-9.9998)
localFrame:setSkewY(-9.9995)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0005)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hand_1)

--Create AnchorPointTimeline
local AnchorPointTimeline = ccs.Timeline:create()

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0, y = 0.5})
AnchorPointTimeline:addFrame(localFrame)

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0, y = 0.5})
AnchorPointTimeline:addFrame(localFrame)

result['animation']:addTimeline(AnchorPointTimeline)
AnchorPointTimeline:setNode(hand_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-62.2308)
localFrame:setY(24.7985)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-62.2308)
localFrame:setY(24.7985)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-62.2308)
localFrame:setY(24.7985)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hand_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hand_2)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(-0.0002)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-10.0000)
localFrame:setSkewY(-10.0002)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hand_2)

--Create AnchorPointTimeline
local AnchorPointTimeline = ccs.Timeline:create()

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0.2054, y = 0.87})
AnchorPointTimeline:addFrame(localFrame)

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0.2054, y = 0.87})
AnchorPointTimeline:addFrame(localFrame)

localFrame = ccs.AnchorPointFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAnchorPoint({x = 0.2054, y = 0.87})
AnchorPointTimeline:addFrame(localFrame)

result['animation']:addTimeline(AnchorPointTimeline)
AnchorPointTimeline:setNode(hand_2)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(20.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(fish)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(fish)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-130.0000)
localFrame:setY(-60.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-136.4819)
localFrame:setY(-60.7201)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-130.0000)
localFrame:setY(-60.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_1_1_3)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_effect_1_1_3)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-5.8081)
localFrame:setSkewY(-5.8082)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_effect_1_1_3)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-80.0000)
localFrame:setY(-60.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-85.0413)
localFrame:setY(-60.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-80.0000)
localFrame:setY(-60.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_1_2_4)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_effect_1_2_4)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-5.4198)
localFrame:setSkewY(-5.4198)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_effect_1_2_4)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(124.7764)
localFrame:setY(-43.5390)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(129.0966)
localFrame:setY(-46.4194)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(124.7764)
localFrame:setY(-43.5390)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_1_4_6)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_effect_1_4_6)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(9.3639)
localFrame:setSkewY(9.3630)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(16.8740)
localFrame:setSkewY(16.8724)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(9.3639)
localFrame:setSkewY(9.3630)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_effect_1_4_6)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(75.5117)
localFrame:setY(-30.0706)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(82.7131)
localFrame:setY(-30.0706)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(75.5117)
localFrame:setY(-30.0706)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_1_3_5)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_effect_1_3_5)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(5.4975)
localFrame:setSkewY(5.4982)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_effect_1_3_5)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(10.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(room_effect)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(room_effect)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(room_effect)

--Create FileDataTimeline
local FileDataTimeline = ccs.Timeline:create()

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
localFrame:setTextureName("hall/friend/fr_pic_dkfj_1.png")
FileDataTimeline:addFrame(localFrame)

result['animation']:addTimeline(FileDataTimeline)
FileDataTimeline:setNode(hall_room_title_2_9)

--Create BlendFuncTimeline
local BlendFuncTimeline = ccs.Timeline:create()

result['animation']:addTimeline(BlendFuncTimeline)
BlendFuncTimeline:setNode(hall_room_title_2_9)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(128.4567)
localFrame:setY(-43.3778)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(129.0602)
localFrame:setY(-45.1882)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_3_14)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_title_light_3_14)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(520.0000)
localFrame:setSkewY(520.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_title_light_3_14)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(85)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(110)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(hall_room_title_light_3_14)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(43)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-32.4290)
localFrame:setY(97.2122)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(232.1451)
localFrame:setY(90.7435)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_1_13)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(51)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-32.4290)
localFrame:setY(97.2122)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(78)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(232.1451)
localFrame:setY(90.7435)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_1_13_0)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(-22.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(-14.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(-22.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(title)
--Create Animation List
local roomact = {name="roomact", startIndex=0, endIndex=120}
result['animation']:addAnimationInfo(roomact)
local stopact = {name="stopact", startIndex=0, endIndex=1}
result['animation']:addAnimationInfo(stopact)

result['root'] = Node
return result;
end

return Result

