--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(102)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(93)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
Node:addChild(panel)

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("hall/task/task_bg_1.png",0)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 15, y = 15, width = 1, height = 1})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(95)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 1170.0000, height = 160.0000})
layout:setLeftMargin(-585.0000)
layout:setRightMargin(-585.0000)
layout:setTopMargin(-80.0000)
layout:setBottomMargin(-80.0000)
panel:addChild(img_bg)

--Create line
local line = ccui.ImageView:create()
line:ignoreContentAdaptWithSize(false)
line:loadTexture("common/com_pic_line_1.png",0)
line:setScale9Enabled(true)
line:setCapInsets({x = 2, y = 1, width = 1, height = 2})
line:setLayoutComponentEnabled(true)
line:setName("line")
line:setTag(94)
line:setCascadeColorEnabled(true)
line:setCascadeOpacityEnabled(true)
line:setPosition(-73.0000, 35.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(line)
layout:setSize({width = 976.0000, height = 4.0000})
layout:setLeftMargin(-561.0000)
layout:setRightMargin(-415.0000)
layout:setTopMargin(-37.0000)
layout:setBottomMargin(33.0000)
panel:addChild(line)

--Create btn_roomrule
local btn_roomrule = ccui.Button:create()
btn_roomrule:ignoreContentAdaptWithSize(false)
btn_roomrule:loadTextureNormal("common/btn/com_btn_blue_min_0.png",0)
btn_roomrule:loadTexturePressed("common/btn/com_btn_blue_min_1.png",0)
btn_roomrule:loadTextureDisabled("common/btn/com_btn_blue_min_2.png",0)
btn_roomrule:setTitleFontSize(14)
btn_roomrule:setTitleColor({r = 65, g = 65, b = 70})
btn_roomrule:setScale9Enabled(true)
btn_roomrule:setCapInsets({x = 19, y = 31, width = 1, height = 2})
btn_roomrule:setLayoutComponentEnabled(true)
btn_roomrule:setName("btn_roomrule")
btn_roomrule:setTag(144)
btn_roomrule:setCascadeColorEnabled(true)
btn_roomrule:setCascadeOpacityEnabled(true)
btn_roomrule:setPosition(496.0800, 49.6482)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_roomrule)
layout:setSize({width = 118.0000, height = 44.0000})
layout:setLeftMargin(437.0800)
layout:setRightMargin(-555.0800)
layout:setTopMargin(-71.6482)
layout:setBottomMargin(27.6482)
panel:addChild(btn_roomrule)

--Create spr_roomrule_title
local spr_roomrule_title = cc.Sprite:create("hall/friend/fr_btn_bfwf.png")
spr_roomrule_title:setName("spr_roomrule_title")
spr_roomrule_title:setTag(145)
spr_roomrule_title:setCascadeColorEnabled(true)
spr_roomrule_title:setCascadeOpacityEnabled(true)
spr_roomrule_title:setPosition(59.0000, 24.0020)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_roomrule_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5455)
layout:setPercentWidth(0.8136)
layout:setPercentHeight(0.6818)
layout:setSize({width = 96.0000, height = 30.0000})
layout:setLeftMargin(11.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(4.9980)
layout:setBottomMargin(9.0020)
spr_roomrule_title:setBlendFunc({src = 1, dst = 771})
btn_roomrule:addChild(spr_roomrule_title)

--Create btn_dissolution
local btn_dissolution = ccui.Button:create()
btn_dissolution:ignoreContentAdaptWithSize(false)
btn_dissolution:loadTextureNormal("common/btn/com_btn_red_0.png",0)
btn_dissolution:loadTexturePressed("common/btn/com_btn_red_1.png",0)
btn_dissolution:loadTextureDisabled("common/btn/com_btn_red_1.png",0)
btn_dissolution:setTitleFontSize(14)
btn_dissolution:setTitleColor({r = 65, g = 65, b = 70})
btn_dissolution:setScale9Enabled(true)
btn_dissolution:setCapInsets({x = 38, y = 11, width = 89, height = 60})
btn_dissolution:setLayoutComponentEnabled(true)
btn_dissolution:setName("btn_dissolution")
btn_dissolution:setTag(149)
btn_dissolution:setCascadeColorEnabled(true)
btn_dissolution:setCascadeOpacityEnabled(true)
btn_dissolution:setPosition(337.0319, -24.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_dissolution)
layout:setSize({width = 158.0000, height = 82.0000})
layout:setLeftMargin(258.0319)
layout:setRightMargin(-416.0319)
layout:setTopMargin(-17.0000)
layout:setBottomMargin(-65.0000)
panel:addChild(btn_dissolution)

--Create spr_dissolution_title
local spr_dissolution_title = cc.Sprite:create("hall/friend/fr_btn_js.png")
spr_dissolution_title:setName("spr_dissolution_title")
spr_dissolution_title:setTag(150)
spr_dissolution_title:setCascadeColorEnabled(true)
spr_dissolution_title:setCascadeOpacityEnabled(true)
spr_dissolution_title:setPosition(79.0000, 44.7310)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_dissolution_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5455)
layout:setPercentWidth(0.4557)
layout:setPercentHeight(0.4878)
layout:setSize({width = 72.0000, height = 40.0000})
layout:setLeftMargin(43.0000)
layout:setRightMargin(43.0000)
layout:setTopMargin(17.2690)
layout:setBottomMargin(24.7310)
spr_dissolution_title:setBlendFunc({src = 1, dst = 771})
btn_dissolution:addChild(spr_dissolution_title)

--Create btn_invitation
local btn_invitation = ccui.Button:create()
btn_invitation:ignoreContentAdaptWithSize(false)
btn_invitation:loadTextureNormal("common/btn/com_btn_green_0.png",0)
btn_invitation:loadTexturePressed("common/btn/com_btn_green_1.png",0)
btn_invitation:loadTextureDisabled("common/btn/com_btn_green_1.png",0)
btn_invitation:setTitleFontSize(14)
btn_invitation:setTitleColor({r = 65, g = 65, b = 70})
btn_invitation:setScale9Enabled(true)
btn_invitation:setCapInsets({x = 38, y = 11, width = 89, height = 60})
btn_invitation:setLayoutComponentEnabled(true)
btn_invitation:setName("btn_invitation")
btn_invitation:setTag(151)
btn_invitation:setCascadeColorEnabled(true)
btn_invitation:setCascadeOpacityEnabled(true)
btn_invitation:setPosition(495.9835, -24.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_invitation)
layout:setSize({width = 158.0000, height = 82.0000})
layout:setLeftMargin(416.9835)
layout:setRightMargin(-574.9835)
layout:setTopMargin(-17.0000)
layout:setBottomMargin(-65.0000)
panel:addChild(btn_invitation)

--Create spr_invitation_title
local spr_invitation_title = cc.Sprite:create("hall/friend/fr_btn_yq.png")
spr_invitation_title:setName("spr_invitation_title")
spr_invitation_title:setTag(152)
spr_invitation_title:setCascadeColorEnabled(true)
spr_invitation_title:setCascadeOpacityEnabled(true)
spr_invitation_title:setPosition(79.0000, 44.7310)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_invitation_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5455)
layout:setPercentWidth(0.4557)
layout:setPercentHeight(0.4878)
layout:setSize({width = 72.0000, height = 40.0000})
layout:setLeftMargin(43.0000)
layout:setRightMargin(43.0000)
layout:setTopMargin(17.2690)
layout:setBottomMargin(24.7310)
spr_invitation_title:setBlendFunc({src = 1, dst = 771})
btn_invitation:addChild(spr_invitation_title)

--Create text_name_title
local text_name_title = ccui.Text:create()
text_name_title:ignoreContentAdaptWithSize(true)
text_name_title:setTextAreaSize({width = 0, height = 0})
text_name_title:setFontSize(23)
text_name_title:setString([[好友约局]])
text_name_title:setLayoutComponentEnabled(true)
text_name_title:setName("text_name_title")
text_name_title:setTag(281)
text_name_title:setCascadeColorEnabled(true)
text_name_title:setCascadeOpacityEnabled(true)
text_name_title:setPosition(-467.5715, 56.0000)
text_name_title:setTextColor({r = 26, g = 77, b = 156})
layout = ccui.LayoutComponent:bindLayoutComponent(text_name_title)
layout:setSize({width = 92.0000, height = 23.0000})
layout:setLeftMargin(-513.5715)
layout:setRightMargin(421.5715)
layout:setTopMargin(-67.5000)
layout:setBottomMargin(44.5000)
panel:addChild(text_name_title)

--Create text_roomid_title
local text_roomid_title = ccui.Text:create()
text_roomid_title:ignoreContentAdaptWithSize(true)
text_roomid_title:setTextAreaSize({width = 0, height = 0})
text_roomid_title:setFontSize(23)
text_roomid_title:setString([[房号：]])
text_roomid_title:setLayoutComponentEnabled(true)
text_roomid_title:setName("text_roomid_title")
text_roomid_title:setTag(282)
text_roomid_title:setCascadeColorEnabled(true)
text_roomid_title:setCascadeOpacityEnabled(true)
text_roomid_title:setAnchorPoint(1.0000, 0.5000)
text_roomid_title:setPosition(-235.6541, 56.0000)
text_roomid_title:setTextColor({r = 26, g = 77, b = 156})
layout = ccui.LayoutComponent:bindLayoutComponent(text_roomid_title)
layout:setSize({width = 69.0000, height = 23.0000})
layout:setLeftMargin(-304.6541)
layout:setRightMargin(235.6541)
layout:setTopMargin(-67.5000)
layout:setBottomMargin(44.5000)
panel:addChild(text_roomid_title)

--Create text_roomid
local text_roomid = ccui.Text:create()
text_roomid:ignoreContentAdaptWithSize(true)
text_roomid:setTextAreaSize({width = 0, height = 0})
text_roomid:setFontSize(23)
text_roomid:setString([[12345678]])
text_roomid:setLayoutComponentEnabled(true)
text_roomid:setName("text_roomid")
text_roomid:setTag(283)
text_roomid:setCascadeColorEnabled(true)
text_roomid:setCascadeOpacityEnabled(true)
text_roomid:setAnchorPoint(0.0000, 0.5000)
text_roomid:setPosition(-234.1346, 56.0000)
text_roomid:setTextColor({r = 26, g = 77, b = 156})
layout = ccui.LayoutComponent:bindLayoutComponent(text_roomid)
layout:setSize({width = 96.0000, height = 23.0000})
layout:setLeftMargin(-234.1346)
layout:setRightMargin(138.1346)
layout:setTopMargin(-67.5000)
layout:setBottomMargin(44.5000)
panel:addChild(text_roomid)

--Create text_duration
local text_duration = ccui.Text:create()
text_duration:ignoreContentAdaptWithSize(true)
text_duration:setTextAreaSize({width = 0, height = 0})
text_duration:setFontSize(23)
text_duration:setString([[24分钟]])
text_duration:setLayoutComponentEnabled(true)
text_duration:setName("text_duration")
text_duration:setTag(284)
text_duration:setCascadeColorEnabled(true)
text_duration:setCascadeOpacityEnabled(true)
text_duration:setAnchorPoint(0.0000, 0.5000)
text_duration:setPosition(-79.6662, 56.0000)
text_duration:setTextColor({r = 195, g = 71, b = 19})
layout = ccui.LayoutComponent:bindLayoutComponent(text_duration)
layout:setSize({width = 70.0000, height = 23.0000})
layout:setLeftMargin(-79.6662)
layout:setRightMargin(9.6662)
layout:setTopMargin(-67.5000)
layout:setBottomMargin(44.5000)
panel:addChild(text_duration)

--Create text_openroom_time
local text_openroom_time = ccui.Text:create()
text_openroom_time:ignoreContentAdaptWithSize(true)
text_openroom_time:setTextAreaSize({width = 0, height = 0})
text_openroom_time:setFontSize(23)
text_openroom_time:setString([[2017-10-25 09:51]])
text_openroom_time:setLayoutComponentEnabled(true)
text_openroom_time:setName("text_openroom_time")
text_openroom_time:setTag(285)
text_openroom_time:setCascadeColorEnabled(true)
text_openroom_time:setCascadeOpacityEnabled(true)
text_openroom_time:setAnchorPoint(0.0000, 0.5000)
text_openroom_time:setPosition(41.6127, 56.0000)
text_openroom_time:setTextColor({r = 26, g = 77, b = 156})
layout = ccui.LayoutComponent:bindLayoutComponent(text_openroom_time)
layout:setSize({width = 192.0000, height = 23.0000})
layout:setLeftMargin(41.6127)
layout:setRightMargin(-233.6127)
layout:setTopMargin(-67.5000)
layout:setBottomMargin(44.5000)
panel:addChild(text_openroom_time)

--Create node_head1
innerCSD = require("ui.common.uiheadstylesimple")
innerProject = innerCSD.create(callBackProvider)
local node_head1 = innerProject.root
node_head1.animation = innerProject.animation
node_head1:setName("node_head1")
node_head1:setTag(74)
node_head1:setCascadeColorEnabled(true)
node_head1:setCascadeOpacityEnabled(true)
node_head1:setPosition(-470.2600, -7.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_head1)
layout:setLeftMargin(-470.2600)
layout:setRightMargin(470.2600)
layout:setTopMargin(7.0000)
layout:setBottomMargin(-7.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_head1:runAction(innerProject.animation)
panel:addChild(node_head1)

--Create node_head2
innerCSD = require("ui.common.uiheadstylesimple")
innerProject = innerCSD.create(callBackProvider)
local node_head2 = innerProject.root
node_head2.animation = innerProject.animation
node_head2:setName("node_head2")
node_head2:setTag(84)
node_head2:setCascadeColorEnabled(true)
node_head2:setCascadeOpacityEnabled(true)
node_head2:setPosition(-261.2300, -7.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_head2)
layout:setLeftMargin(-261.2300)
layout:setRightMargin(261.2300)
layout:setTopMargin(7.0000)
layout:setBottomMargin(-7.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_head2:runAction(innerProject.animation)
panel:addChild(node_head2)

--Create node_head3
innerCSD = require("ui.common.uiheadstylesimple")
innerProject = innerCSD.create(callBackProvider)
local node_head3 = innerProject.root
node_head3.animation = innerProject.animation
node_head3:setName("node_head3")
node_head3:setTag(94)
node_head3:setCascadeColorEnabled(true)
node_head3:setCascadeOpacityEnabled(true)
node_head3:setPosition(-43.8800, -7.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_head3)
layout:setLeftMargin(-43.8800)
layout:setRightMargin(43.8800)
layout:setTopMargin(7.0000)
layout:setBottomMargin(-7.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_head3:runAction(innerProject.animation)
panel:addChild(node_head3)

--Create node_head4
innerCSD = require("ui.common.uiheadstylesimple")
innerProject = innerCSD.create(callBackProvider)
local node_head4 = innerProject.root
node_head4.animation = innerProject.animation
node_head4:setName("node_head4")
node_head4:setTag(104)
node_head4:setCascadeColorEnabled(true)
node_head4:setCascadeOpacityEnabled(true)
node_head4:setPosition(161.4000, -7.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_head4)
layout:setLeftMargin(161.4000)
layout:setRightMargin(-161.4000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(-7.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_head4:runAction(innerProject.animation)
panel:addChild(node_head4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

