--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(864)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
Node:addChild(panel)

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("common/layerbg/com_bg_pic_3.png",0)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 135, y = 92, width = 20, height = 28})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(24)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 1062.0000, height = 389.0000})
layout:setLeftMargin(-531.0000)
layout:setRightMargin(-531.0000)
layout:setTopMargin(-194.5000)
layout:setBottomMargin(-194.5000)
panel:addChild(img_bg)

--Create img_bg_1
local img_bg_1 = ccui.ImageView:create()
img_bg_1:ignoreContentAdaptWithSize(false)
img_bg_1:loadTexture("common/layerbg/com_bg_pic_tmbg.png",0)
img_bg_1:setScale9Enabled(true)
img_bg_1:setCapInsets({x = 37, y = 5, width = 1, height = 4})
img_bg_1:setLayoutComponentEnabled(true)
img_bg_1:setName("img_bg_1")
img_bg_1:setTag(866)
img_bg_1:setCascadeColorEnabled(true)
img_bg_1:setCascadeOpacityEnabled(true)
img_bg_1:setPosition(531.0000, 168.0000)
img_bg_1:setColor({r = 0, g = 16, b = 86})
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4319)
layout:setPercentWidth(0.9680)
layout:setPercentHeight(0.7712)
layout:setSize({width = 1028.0000, height = 300.0000})
layout:setLeftMargin(17.0000)
layout:setRightMargin(17.0000)
layout:setTopMargin(71.0000)
layout:setBottomMargin(18.0000)
img_bg:addChild(img_bg_1)

--Create spr_title
local spr_title = cc.Sprite:create("battle/gunupgrade/bl_pic_tittle_jspb.png")
spr_title:setName("spr_title")
spr_title:setTag(25)
spr_title:setCascadeColorEnabled(true)
spr_title:setCascadeOpacityEnabled(true)
spr_title:setPosition(0.0000, 152.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_title)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 184.0000, height = 42.0000})
layout:setLeftMargin(-92.0000)
layout:setRightMargin(-92.0000)
layout:setTopMargin(-173.0000)
layout:setBottomMargin(131.0000)
spr_title:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_title)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("common/btn/com_btn_close_0.png",0)
btn_close:loadTexturePressed("common/btn/com_btn_close_1.png",0)
btn_close:loadTextureDisabled("common/btn/com_btn_close_1.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 40, height = 48})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(124)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(500.0000, 161.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(465.0000)
layout:setRightMargin(-535.0000)
layout:setTopMargin(-196.0000)
layout:setBottomMargin(126.0000)
panel:addChild(btn_close)

--Create spr_zgpb
local spr_zgpb = cc.Sprite:create("battle/gunupgrade/bl_pic_zgpb.png")
spr_zgpb:setName("spr_zgpb")
spr_zgpb:setTag(508)
spr_zgpb:setCascadeColorEnabled(true)
spr_zgpb:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_zgpb)
layout:setSize({width = 678.0000, height = 78.0000})
layout:setLeftMargin(-339.0000)
layout:setRightMargin(-339.0000)
layout:setTopMargin(-39.0000)
layout:setBottomMargin(-39.0000)
spr_zgpb:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_zgpb)

--Create node_item
local node_item=cc.Node:create()
node_item:setName("node_item")
node_item:setTag(117)
node_item:setCascadeColorEnabled(true)
node_item:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_item)
panel:addChild(node_item)

--Create node_item_1
innerCSD = require("ui.battle.unlockcannon.uiunlockcannonitem")
innerProject = innerCSD.create(callBackProvider)
local node_item_1 = innerProject.root
node_item_1.animation = innerProject.animation
node_item_1:setName("node_item_1")
node_item_1:setTag(51)
node_item_1:setCascadeColorEnabled(true)
node_item_1:setCascadeOpacityEnabled(true)
node_item_1:setPosition(-405.0000, -25.0000)
node_item_1:setScaleX(0.8000)
node_item_1:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_item_1)
layout:setLeftMargin(-405.0000)
layout:setRightMargin(405.0000)
layout:setTopMargin(25.0000)
layout:setBottomMargin(-25.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_item_1:runAction(innerProject.animation)
node_item:addChild(node_item_1)

--Create node_item_2
innerCSD = require("ui.battle.unlockcannon.uiunlockcannonitem")
innerProject = innerCSD.create(callBackProvider)
local node_item_2 = innerProject.root
node_item_2.animation = innerProject.animation
node_item_2:setName("node_item_2")
node_item_2:setTag(70)
node_item_2:setCascadeColorEnabled(true)
node_item_2:setCascadeOpacityEnabled(true)
node_item_2:setPosition(-208.0000, -25.0000)
node_item_2:setScaleX(0.8000)
node_item_2:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_item_2)
layout:setLeftMargin(-208.0000)
layout:setRightMargin(208.0000)
layout:setTopMargin(25.0000)
layout:setBottomMargin(-25.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_item_2:runAction(innerProject.animation)
node_item:addChild(node_item_2)

--Create node_item_3
innerCSD = require("ui.battle.unlockcannon.uiunlockcannonitem")
innerProject = innerCSD.create(callBackProvider)
local node_item_3 = innerProject.root
node_item_3.animation = innerProject.animation
node_item_3:setName("node_item_3")
node_item_3:setTag(32)
node_item_3:setCascadeColorEnabled(true)
node_item_3:setCascadeOpacityEnabled(true)
node_item_3:setPosition(0.0000, -25.0000)
node_item_3:setScaleX(0.9000)
node_item_3:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_item_3)
layout:setTopMargin(25.0000)
layout:setBottomMargin(-25.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_item_3:runAction(innerProject.animation)
node_item:addChild(node_item_3)

--Create node_item_4
innerCSD = require("ui.battle.unlockcannon.uiunlockcannonitem")
innerProject = innerCSD.create(callBackProvider)
local node_item_4 = innerProject.root
node_item_4.animation = innerProject.animation
node_item_4:setName("node_item_4")
node_item_4:setTag(89)
node_item_4:setCascadeColorEnabled(true)
node_item_4:setCascadeOpacityEnabled(true)
node_item_4:setPosition(208.0000, -25.0000)
node_item_4:setScaleX(0.8000)
node_item_4:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_item_4)
layout:setLeftMargin(208.0000)
layout:setRightMargin(-208.0000)
layout:setTopMargin(25.0000)
layout:setBottomMargin(-25.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_item_4:runAction(innerProject.animation)
node_item:addChild(node_item_4)

--Create node_item_5
innerCSD = require("ui.battle.unlockcannon.uiunlockcannonitem")
innerProject = innerCSD.create(callBackProvider)
local node_item_5 = innerProject.root
node_item_5.animation = innerProject.animation
node_item_5:setName("node_item_5")
node_item_5:setTag(108)
node_item_5:setCascadeColorEnabled(true)
node_item_5:setCascadeOpacityEnabled(true)
node_item_5:setPosition(405.0000, -25.0000)
node_item_5:setScaleX(0.8000)
node_item_5:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_item_5)
layout:setLeftMargin(405.0000)
layout:setRightMargin(-405.0000)
layout:setTopMargin(25.0000)
layout:setBottomMargin(-25.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_item_5:runAction(innerProject.animation)
node_item:addChild(node_item_5)

--Create spr_effect_unlock
local spr_effect_unlock = cc.Sprite:create("battle/effect/effect_unlock_1.png")
spr_effect_unlock:setName("spr_effect_unlock")
spr_effect_unlock:setTag(119)
spr_effect_unlock:setCascadeColorEnabled(true)
spr_effect_unlock:setCascadeOpacityEnabled(true)
spr_effect_unlock:setPosition(0.0000, -24.0000)
spr_effect_unlock:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_effect_unlock)
layout:setSize({width = 258.0000, height = 321.0000})
layout:setLeftMargin(-129.0000)
layout:setRightMargin(-129.0000)
layout:setTopMargin(-136.5000)
layout:setBottomMargin(-184.5000)
spr_effect_unlock:setBlendFunc({src = 770, dst = 1})
panel:addChild(spr_effect_unlock)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(60)
result['animation']:setTimeSpeed(1.0000)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0100)
localFrame:setScaleY(1.0100)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(spr_effect_unlock)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(spr_effect_unlock)
--Create Animation List
local unlock_prompt = {name="unlock_prompt", startIndex=0, endIndex=60}
result['animation']:addAnimationInfo(unlock_prompt)

result['root'] = Node
return result;
end

return Result

