--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("battle/friend/friend_bg_6.png",0)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 0, y = 40, width = 8, height = 10})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(27)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setAnchorPoint(0.0000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 156.0000, height = 259.0000})
layout:setRightMargin(-156.0000)
layout:setTopMargin(-129.5000)
layout:setBottomMargin(-129.5000)
Node:addChild(img_bg)

--Create img_rank_my_bg
local img_rank_my_bg = ccui.ImageView:create()
img_rank_my_bg:ignoreContentAdaptWithSize(false)
img_rank_my_bg:loadTexture("battle/friend/friend_bg_3.png",0)
img_rank_my_bg:setScale9Enabled(true)
img_rank_my_bg:setCapInsets({x = -10, y = 1, width = 20, height = 8})
img_rank_my_bg:setLayoutComponentEnabled(true)
img_rank_my_bg:setName("img_rank_my_bg")
img_rank_my_bg:setTag(32)
img_rank_my_bg:setCascadeColorEnabled(true)
img_rank_my_bg:setCascadeOpacityEnabled(true)
img_rank_my_bg:setPosition(70.0000, 170.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_rank_my_bg)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.6564)
layout:setPercentWidth(0.9615)
layout:setPercentHeight(0.1544)
layout:setSize({width = 150.0000, height = 40.0000})
layout:setLeftMargin(-5.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(69.0000)
layout:setBottomMargin(150.0000)
img_bg:addChild(img_rank_my_bg)

--Create node_rank_1
innerCSD = require("ui.battle.friend.uifriendrankitem")
innerProject = innerCSD.create(callBackProvider)
local node_rank_1 = innerProject.root
node_rank_1.animation = innerProject.animation
node_rank_1:setName("node_rank_1")
node_rank_1:setTag(233)
node_rank_1:setCascadeColorEnabled(true)
node_rank_1:setCascadeOpacityEnabled(true)
node_rank_1:setPosition(70.0000, 170.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_rank_1)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.6564)
layout:setLeftMargin(70.0000)
layout:setRightMargin(86.0000)
layout:setTopMargin(89.0000)
layout:setBottomMargin(170.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_rank_1:runAction(innerProject.animation)
img_bg:addChild(node_rank_1)

--Create node_rank_2
innerCSD = require("ui.battle.friend.uifriendrankitem")
innerProject = innerCSD.create(callBackProvider)
local node_rank_2 = innerProject.root
node_rank_2.animation = innerProject.animation
node_rank_2:setName("node_rank_2")
node_rank_2:setTag(238)
node_rank_2:setCascadeColorEnabled(true)
node_rank_2:setCascadeOpacityEnabled(true)
node_rank_2:setPosition(70.0000, 130.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_rank_2)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.5019)
layout:setLeftMargin(70.0000)
layout:setRightMargin(86.0000)
layout:setTopMargin(129.0000)
layout:setBottomMargin(130.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_rank_2:runAction(innerProject.animation)
img_bg:addChild(node_rank_2)

--Create node_rank_3
innerCSD = require("ui.battle.friend.uifriendrankitem")
innerProject = innerCSD.create(callBackProvider)
local node_rank_3 = innerProject.root
node_rank_3.animation = innerProject.animation
node_rank_3:setName("node_rank_3")
node_rank_3:setTag(243)
node_rank_3:setCascadeColorEnabled(true)
node_rank_3:setCascadeOpacityEnabled(true)
node_rank_3:setPosition(70.0000, 90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_rank_3)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.3475)
layout:setLeftMargin(70.0000)
layout:setRightMargin(86.0000)
layout:setTopMargin(169.0000)
layout:setBottomMargin(90.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_rank_3:runAction(innerProject.animation)
img_bg:addChild(node_rank_3)

--Create node_rank_4
innerCSD = require("ui.battle.friend.uifriendrankitem")
innerProject = innerCSD.create(callBackProvider)
local node_rank_4 = innerProject.root
node_rank_4.animation = innerProject.animation
node_rank_4:setName("node_rank_4")
node_rank_4:setTag(248)
node_rank_4:setCascadeColorEnabled(true)
node_rank_4:setCascadeOpacityEnabled(true)
node_rank_4:setPosition(70.0000, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_rank_4)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.1931)
layout:setLeftMargin(70.0000)
layout:setRightMargin(86.0000)
layout:setTopMargin(209.0000)
layout:setBottomMargin(50.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_rank_4:runAction(innerProject.animation)
img_bg:addChild(node_rank_4)

--Create spr_rank
local spr_rank = cc.Sprite:create("battle/friend/friend_text_pm.png")
spr_rank:setName("spr_rank")
spr_rank:setTag(136)
spr_rank:setCascadeColorEnabled(true)
spr_rank:setCascadeOpacityEnabled(true)
spr_rank:setPosition(28.0000, 95.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_rank)
layout:setSize({width = 36.0000, height = 18.0000})
layout:setLeftMargin(10.0000)
layout:setRightMargin(-46.0000)
layout:setTopMargin(-104.0000)
layout:setBottomMargin(86.0000)
spr_rank:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_rank)

--Create spr_amount
local spr_amount = cc.Sprite:create("battle/friend/friend_text_jf.png")
spr_amount:setName("spr_amount")
spr_amount:setTag(137)
spr_amount:setCascadeColorEnabled(true)
spr_amount:setCascadeOpacityEnabled(true)
spr_amount:setPosition(95.0000, 95.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_amount)
layout:setSize({width = 36.0000, height = 18.0000})
layout:setLeftMargin(77.0000)
layout:setRightMargin(-113.0000)
layout:setTopMargin(-104.0000)
layout:setBottomMargin(86.0000)
spr_amount:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_amount)

--Create spr_light_split
local spr_light_split = cc.Sprite:create("battle/friend/friend_light_6.png")
spr_light_split:setName("spr_light_split")
spr_light_split:setTag(138)
spr_light_split:setCascadeColorEnabled(true)
spr_light_split:setCascadeOpacityEnabled(true)
spr_light_split:setPosition(71.4489, 75.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_light_split)
layout:setSize({width = 148.0000, height = 2.0000})
layout:setLeftMargin(-2.5511)
layout:setRightMargin(-145.4489)
layout:setTopMargin(-76.0000)
layout:setBottomMargin(74.0000)
spr_light_split:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_light_split)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

