--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(102)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(4)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
Node:addChild(panel)

--Create spr_head
local spr_head = cc.Sprite:create("hall/friend/fr_pic_photo_bg.png")
spr_head:setName("spr_head")
spr_head:setTag(4)
spr_head:setCascadeColorEnabled(true)
spr_head:setCascadeOpacityEnabled(true)
spr_head:setPosition(-63.9116, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_head)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 74.0000, height = 74.0000})
layout:setLeftMargin(-100.9116)
layout:setRightMargin(26.9116)
layout:setTopMargin(-37.0000)
layout:setBottomMargin(-37.0000)
spr_head:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_head)

--Create spr_loop
local spr_loop = cc.Sprite:create("hall/friend/fr_pic_photo_bg_1.png")
spr_loop:setName("spr_loop")
spr_loop:setTag(11)
spr_loop:setCascadeColorEnabled(true)
spr_loop:setCascadeOpacityEnabled(true)
spr_loop:setPosition(0.6272, -0.0004)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_loop)
layout:setSize({width = 80.0000, height = 80.0000})
layout:setLeftMargin(-39.3728)
layout:setRightMargin(-40.6272)
layout:setTopMargin(-39.9996)
layout:setBottomMargin(-40.0004)
spr_loop:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_loop)

--Create spr_ready
local spr_ready = cc.Sprite:create("hall/friend/fr_pic_yzb.png")
spr_ready:setName("spr_ready")
spr_ready:setTag(165)
spr_ready:setCascadeColorEnabled(true)
spr_ready:setCascadeOpacityEnabled(true)
spr_ready:setPosition(49.2759, 25.7889)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_ready)
layout:setSize({width = 78.0000, height = 30.0000})
layout:setLeftMargin(10.2759)
layout:setRightMargin(-88.2759)
layout:setTopMargin(-40.7889)
layout:setBottomMargin(10.7889)
spr_ready:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_ready)

--Create text_id_title
local text_id_title = ccui.Text:create()
text_id_title:ignoreContentAdaptWithSize(true)
text_id_title:setTextAreaSize({width = 0, height = 0})
text_id_title:setFontSize(18)
text_id_title:setString([[ID ：]])
text_id_title:setLayoutComponentEnabled(true)
text_id_title:setName("text_id_title")
text_id_title:setTag(6)
text_id_title:setCascadeColorEnabled(true)
text_id_title:setCascadeOpacityEnabled(true)
text_id_title:setAnchorPoint(1.0000, 0.5000)
text_id_title:setPosition(-35.6069, -41.7890)
text_id_title:setTextColor({r = 26, g = 77, b = 156})
layout = ccui.LayoutComponent:bindLayoutComponent(text_id_title)
layout:setSize({width = 45.0000, height = 18.0000})
layout:setLeftMargin(-80.6069)
layout:setRightMargin(35.6069)
layout:setTopMargin(32.7890)
layout:setBottomMargin(-50.7890)
panel:addChild(text_id_title)

--Create text_name_title
local text_name_title = ccui.Text:create()
text_name_title:ignoreContentAdaptWithSize(true)
text_name_title:setTextAreaSize({width = 0, height = 0})
text_name_title:setFontSize(18)
text_name_title:setString([[昵称：]])
text_name_title:setLayoutComponentEnabled(true)
text_name_title:setName("text_name_title")
text_name_title:setTag(7)
text_name_title:setCascadeColorEnabled(true)
text_name_title:setCascadeOpacityEnabled(true)
text_name_title:setAnchorPoint(1.0000, 0.5000)
text_name_title:setPosition(-35.8403, -60.0544)
text_name_title:setTextColor({r = 26, g = 77, b = 156})
layout = ccui.LayoutComponent:bindLayoutComponent(text_name_title)
layout:setSize({width = 54.0000, height = 18.0000})
layout:setLeftMargin(-89.8403)
layout:setRightMargin(35.8403)
layout:setTopMargin(51.0544)
layout:setBottomMargin(-69.0544)
panel:addChild(text_name_title)

--Create text_name
local text_name = ccui.Text:create()
text_name:ignoreContentAdaptWithSize(true)
text_name:setTextAreaSize({width = 0, height = 0})
text_name:setFontSize(18)
text_name:setString([[名字有七个字啊]])
text_name:setLayoutComponentEnabled(true)
text_name:setName("text_name")
text_name:setTag(8)
text_name:setCascadeColorEnabled(true)
text_name:setCascadeOpacityEnabled(true)
text_name:setAnchorPoint(0.0000, 0.5000)
text_name:setPosition(-36.9397, -60.2155)
text_name:setTextColor({r = 26, g = 77, b = 156})
layout = ccui.LayoutComponent:bindLayoutComponent(text_name)
layout:setSize({width = 126.0000, height = 18.0000})
layout:setLeftMargin(-36.9397)
layout:setRightMargin(-89.0603)
layout:setTopMargin(51.2155)
layout:setBottomMargin(-69.2155)
panel:addChild(text_name)

--Create text_id
local text_id = ccui.Text:create()
text_id:ignoreContentAdaptWithSize(true)
text_id:setTextAreaSize({width = 0, height = 0})
text_id:setFontSize(18)
text_id:setString([[12345678912]])
text_id:setLayoutComponentEnabled(true)
text_id:setName("text_id")
text_id:setTag(9)
text_id:setCascadeColorEnabled(true)
text_id:setCascadeOpacityEnabled(true)
text_id:setAnchorPoint(0.0000, 0.5000)
text_id:setPosition(-36.7796, -41.8777)
text_id:setTextColor({r = 26, g = 77, b = 156})
layout = ccui.LayoutComponent:bindLayoutComponent(text_id)
layout:setSize({width = 99.0000, height = 18.0000})
layout:setLeftMargin(-36.7796)
layout:setRightMargin(-62.2204)
layout:setTopMargin(32.8777)
layout:setBottomMargin(-50.8777)
panel:addChild(text_id)

--Create text_score_title
local text_score_title = ccui.Text:create()
text_score_title:ignoreContentAdaptWithSize(true)
text_score_title:setTextAreaSize({width = 0, height = 0})
text_score_title:setFontSize(22)
text_score_title:setString([[积分:]])
text_score_title:setLayoutComponentEnabled(true)
text_score_title:setName("text_score_title")
text_score_title:setTag(11)
text_score_title:setCascadeColorEnabled(true)
text_score_title:setCascadeOpacityEnabled(true)
text_score_title:setAnchorPoint(1.0000, 0.5000)
text_score_title:setPosition(27.1344, -3.4064)
text_score_title:setTextColor({r = 195, g = 71, b = 19})
layout = ccui.LayoutComponent:bindLayoutComponent(text_score_title)
layout:setSize({width = 55.0000, height = 22.0000})
layout:setLeftMargin(-27.8656)
layout:setRightMargin(-27.1344)
layout:setTopMargin(-7.5936)
layout:setBottomMargin(-14.4064)
panel:addChild(text_score_title)

--Create text_score
local text_score = ccui.Text:create()
text_score:ignoreContentAdaptWithSize(true)
text_score:setTextAreaSize({width = 0, height = 0})
text_score:setFontSize(22)
text_score:setString([[123456]])
text_score:setLayoutComponentEnabled(true)
text_score:setName("text_score")
text_score:setTag(12)
text_score:setCascadeColorEnabled(true)
text_score:setCascadeOpacityEnabled(true)
text_score:setAnchorPoint(0.0000, 0.5000)
text_score:setPosition(27.5270, -2.4664)
text_score:setTextColor({r = 195, g = 71, b = 19})
layout = ccui.LayoutComponent:bindLayoutComponent(text_score)
layout:setSize({width = 66.0000, height = 22.0000})
layout:setLeftMargin(27.5270)
layout:setRightMargin(-93.5270)
layout:setTopMargin(-8.5336)
layout:setBottomMargin(-13.4664)
panel:addChild(text_score)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

