--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.ImageView:create()
panel:ignoreContentAdaptWithSize(false)
panel:loadTexture("hall/monthcard/monthcard_box_bg.png",0)
panel:setScale9Enabled(true)
panel:setCapInsets({x = 32, y = 86, width = 2, height = 6})
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(128)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 234.0000, height = 176.0000})
layout:setLeftMargin(-117.0000)
layout:setRightMargin(-117.0000)
layout:setTopMargin(-88.0000)
layout:setBottomMargin(-88.0000)
Node:addChild(panel)

--Create image_bg_word
local image_bg_word = ccui.ImageView:create()
image_bg_word:ignoreContentAdaptWithSize(false)
image_bg_word:loadTexture("hall/monthcard/monthcard_box_title.png",0)
image_bg_word:setScale9Enabled(true)
image_bg_word:setCapInsets({x = 49, y = 16, width = 1, height = 18})
image_bg_word:setLayoutComponentEnabled(true)
image_bg_word:setName("image_bg_word")
image_bg_word:setTag(129)
image_bg_word:setCascadeColorEnabled(true)
image_bg_word:setCascadeOpacityEnabled(true)
image_bg_word:setPosition(117.0000, 40.2336)
layout = ccui.LayoutComponent:bindLayoutComponent(image_bg_word)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2286)
layout:setPercentWidth(1.0256)
layout:setPercentHeight(0.2841)
layout:setSize({width = 240.0000, height = 50.0000})
layout:setLeftMargin(-3.0000)
layout:setRightMargin(-3.0000)
layout:setTopMargin(110.7664)
layout:setBottomMargin(15.2336)
panel:addChild(image_bg_word)

--Create spr_prop
local spr_prop = cc.Sprite:create("common/prop/prop_005.png")
spr_prop:setName("spr_prop")
spr_prop:setTag(130)
spr_prop:setCascadeColorEnabled(true)
spr_prop:setCascadeOpacityEnabled(true)
spr_prop:setPosition(117.0000, 114.9984)
spr_prop:setRotationSkewY(0.0022)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_prop)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6534)
layout:setPercentWidth(0.4786)
layout:setPercentHeight(0.6364)
layout:setSize({width = 112.0000, height = 112.0000})
layout:setLeftMargin(61.0000)
layout:setRightMargin(61.0000)
layout:setTopMargin(5.0016)
layout:setBottomMargin(58.9984)
spr_prop:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_prop)

--Create spr_name
local spr_name = cc.Sprite:create("hall/monthcard/monthcard_pic_name_5.png")
spr_name:setName("spr_name")
spr_name:setTag(131)
spr_name:setCascadeColorEnabled(true)
spr_name:setCascadeOpacityEnabled(true)
spr_name:setPosition(117.0000, 38.1755)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_name)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2169)
layout:setPercentWidth(0.5812)
layout:setPercentHeight(0.1818)
layout:setSize({width = 136.0000, height = 32.0000})
layout:setLeftMargin(49.0000)
layout:setRightMargin(49.0000)
layout:setTopMargin(121.8245)
layout:setBottomMargin(22.1755)
spr_name:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

